config/routes.rb
Rails.application.routes.draw do
  root "restaurants#index"
  devise_for :users
  resources :restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates :description, presence: true, length: { minimum: 20 }
  validates :rating, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5, only_integer: true}
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["Thai", "Mexican", "American", "Vietnamese", "Peruvian"].sort
  has_one_attached :image
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 20 }
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller?
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:category].present?
      @restaurants = policy_scope(Restaurant).where(category: params[:category])
    else
      @restaurants = policy_scope(Restaurant)
    end
    respond_to do |format|
      format.html
      format.text { render partial: 'restaurants/list', locals: { restaurants: @restaurants }, formats: [:html] }
    end
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    authorize @restaurant
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @restaurant.user = current_user
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :category, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoustonRestaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-indigo-50">
    <div class="container mx-auto mt-16">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_list.html.erb
<div class="grid grid-cols-3 gap-4" data-refresh-list-target="list">
  <% @restaurants.each do |restaurant| %>
    <%= link_to restaurant_path(restaurant) do %>
      <article class="restaurant-card group text-center relative rounded h-40 hover:bg-blue-100 ring-0 ring-indigo-400 shadow-sm hover:ring-2 hover:ring-indigo-400 transition duration-300" style="background:linear-gradient(to right, rgba(230, 230, 230, 0.5), rgba(230, 230, 230, 0.5)),url(<%= rails_blob_url(restaurant.image) if restaurant.image.attached?%>)">
        <div class="absolute bottom-0 w-full text-center bg-gray-100">
          <h2 class="text-lg font-semibold group-hover:underline transition duration-300">
            <%= restaurant.name %>
          </h2>
        </div>
      </article>
    <% end %>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<%= link_to restaurant_path(restaurant) do %>
  <article class="restaurant-card group text-center relative rounded h-40 hover:bg-blue-100 ring-0 ring-indigo-400 shadow-sm hover:ring-2 hover:ring-indigo-400 transition duration-300" style="background:linear-gradient(to right, rgba(230, 230, 230, 0.5), rgba(230, 230, 230, 0.5)),url(<%= rails_blob_url(restaurant.image) if restaurant.image.attached?%>)">
    <div class="absolute bottom-0 w-full text-center bg-gray-100">
      <h2 class="text-lg font-semibold group-hover:underline transition duration-300">
        <%= restaurant.name %>
      </h2>
    </div>
  </article>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Update information on <%= @restaurant.name %></h1>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :category, collection: Restaurant::CATEGORIES, include_blank: false %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1 class="text-center text-2xl">Restaurants</h1>
<div data-controller="refresh-list">
  <%= form_with url: restaurants_path, class: "w-3/4 m-auto flex justify-evenly mt-12 mb-12", data: { refresh_list_target: 'form' } do |f| %>
    <% Restaurant::CATEGORIES.each_with_index do |category, index| %>
      <div class="tag-item">
        <%= f.radio_button :category, category, class: "my-class", data: { refresh_list_target: 'input', refresh_list_food_value: category, action: "click->refresh-list#update" } %>
        <%= f.label "category_#{category.downcase}", category %>
      </div>
    <% end %>
    <div class="tag-item">
      <%= f.radio_button :category, "", class: "my-class", data: { refresh_list_target: 'input', refresh_list_food_value: "", action: "click->refresh-list#update" } %>
      <%= f.label "", "Refresh" %>
    </div>
  <% end %>
  <%= render "restaurants/list" %>
</div>

app/views/restaurants/new.html.erb
<h1>Add new restaurant</h1>
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :category, collection: Restaurant::CATEGORIES, include_blank: false %>
  <%= f.input :image, as: :file, label: "Image" %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="text-center">
  <%= link_to "Back to list", restaurants_path, class: "absolute left-0.5 py-2 px-5 underline" %>
  <h1><%= @restaurant.name %></h1>
  <%= image_tag @restaurant.image, class: "m-auto" if @restaurant.image.attached? %>
  <p><%= @restaurant.description %></p>
  <p><%= @restaurant.category.capitalize %></p>
</div>